# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 89cf0b49f4934778f251d91e120172af2d3ea1c3da243d547bdd6b41c3929c96e28f962c9d1ab5077e3650a89298a89ddb57360e484b0d1d617ea95d915363eb

test:
  secret_key_base: 53560df0f3ff5ea609fd0f66a2520566c50d4c63be565ff41bba2f623baa84ca10336a79521c6baf2d1cf7a7e4871e66af2cb414a7d2fd1397b621d3fb230475

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
